name: 'green_finance'
version: '1.0.0'
config-version: 2

profile: 'bigquery'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  green_finance:
    staging:
      +materialized: table
      +schema: staging
    intermediate:
      +materialized: table
      +schema: intermediate
    marts:
      +materialized: table
      +schema: marts
      crypto_mart:
        +schema: marts_crypto
      stock_mart:
        +schema: marts_stock
      green_finance:
        +schema: marts_green_finance

vars:
  raw_database: 'devops-practice-449210'
  raw_schema: 'finboard'