name: Terraform GCP Service Account Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

env:
  TF_VERSION: "1.8.5"  # Latest stable terraform version
  GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  REGION: ${{ secrets.REGION }}

jobs:
  CREATE_GCP_SA_KEY:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write  # OIDC authentication avec GCP

    steps:
      # Check out github repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set-up terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      # Authentication avec GCP en utilisant OIDC (méthode recommandée pour la sécurité)
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ env.GOOGLE_CREDENTIALS }}
          project_id: ${{ env.PROJECT_ID }}

      # écraser terraform variables avec les github secrets
      - name: Set Terraform variables
        run: |
          echo "project_id = \"${{ env.PROJECT_ID }}\"" >> terraform/terraform.tfvars
          echo "region = \"${{ env.REGION }}\"" >> terraform/terraform.tfvars

      # Init Terraform
      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      # Terraform Plan (Dry-Run terraform en mode test) 
      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan -out=tfplan

      # Terraform Apply (déploiement quand pull request validé)
      - name: Terraform Apply
        if: github.event_name == 'push'
        working-directory: terraform
        run: terraform apply -auto-approve tfplan
