version: 2

sources:
  - name: finboard
    database: devops-practice-449210
    schema: finboard
    tables:
      - name: green_crypto_bkp
      - name: green_crypto_carbon_bkp
      - name: green_stock_bkp
      - name: green_stock_carbon_bkp
      - name: stocks_finance_bkp