version: 2

sources:
  - name: finboard
    database: devops-practice-449210
    schema: finboard
    tables:
      - name: green_crypto
      - name: green_crypto_carbon_mj
      - name: green_stock
      - name: green_stock_bkp
      - name: green_stock_carbon
      - name: stocks_finance
      - name: raw_coincap_prices
      - name: raw_finnhub_financials
      - name: raw_green_crypto
      - name: raw_green_crypto_carbon
      - name: raw_green_stock
      - name: raw_green_stock_carbon